-   title: 리뷰 API인 Crema API 도입 프로젝트
    index: 1
    period: 2023.10 ~ 2024.9
    info : |
        * Spring batch
        * Java
        * Spring
        * Rest API
    person: 
        * 기획 1명, 프론트엔드 1명, 백엔드 1명
    incharge: |
        * Back-End 개발
        * Back Office 개발
        * H Fashion몰, EQL몰 인터페이스, 배치 개발
    description: |
        * 상품, 주문, 주문상세&클레임, 리뷰, 카테고리 API 개발 및 연동 _(`23.10 - `24.02)_
        * 각 API 단 건 전송을 <mark>List로 변경하여 전송하는 v2 개발</mark> _(`24.03 - `24.08)_
        * 인터페이스 내역 감소로 인한 장애 사전 대응 작업
            * 주문 36만건 → 1만건, 결과: 누적 데이터 <mark>97%감소</mark>
            * 주문 상세&클레임 67만건 → 8천건, 결과: 누적 데이터 <mark>98%감소</mark>
            * 상품 3만건 → 2천건, 결과: 누적 데이터 <mark>94%감소</mark>
        * FitProduct API 개발을 위해 상품 상세 사이즈 정보 전체 파싱 개발
        * Crema API인 주문, 주문상세, 클레임 쿼리 <mark>속도개선</mark>을 위해 전체 수정 작업 진행
            * 주문 <mark>3.19sec → 0.02sec</mark>
            * 주문상세 <mark>3.73sec → 0.47sec</mark>
            * 클레임 <mark>2.96sec → 0.13sec</mark>
        * H패션몰 H.Plus 포인트 적립에서 한섬 마일리지로 적립 전환을 위한 마일리지 API 개발

-   title: 타미힐피거 브랜드관 및 무스너클 브랜드관 신규 개발 프로젝트
    index: 2
    period: 2023.2 ~ 2023.8
    info : |
        * Spring
        * JSP
        * jQuery
    person: 
        * 총 수행사 기획 3명, 개발 6명, 디자이너 2명, 퍼블리셔 2명
        * 현대쪽 기획 2명, 개발 3명
    incharge: |
        * 프로젝트 매니징 (PM)
        * QA
        * Back-End 개발
        * Front-End 개발
        * Back Office 개발
        * H Fashion몰 개발
    description: |
        * 전체 페이지 상품이 아닌 <mark>브랜드관 전용 검색</mark> 기능 개발
        * H패션몰 내 타미힐피거, 무스너클만의 고유 색상을 가진 새로운 브랜드관 개발
        * 브랜드만의 콘텐츠 연결 - 매거진, 리뷰, 기획전, 이벤트 연동

-   title: 해외 브랜드 편집샵 입점 및 모바일 메인페이지 UI/UX 리뉴얼
    index: 3
    period: 2022.10 ~ 2023.3
    info : |
        * Spring batch
        * Java
        * JSP
        * JavaScript
        * jQuery
    person: 
        * 기획 2명, 개발 2명
    incharge: |
        * Back-End 개발
        * Front-End 개발
        * Back Office 개발
        * H Fashion몰 개발
    description: |
        *  <mark>300개 이상</mark> 해외 브랜드 편집샵 입점 개발
            * PC/MO 브랜드 이름으로 검색페이지 개발(영어/한글)
            * 브랜드 북마크 개발
        * <mark>모바일 메인 페이지</mark> 전체 리뉴얼
            * 메인 페이지 내 코너모듈마다 1:1로 연결되던 로직을 1:N로직으로 전체 개선하여 속도개선
        

-   title: 고객 관심 채팅 분석 플랫폼 (라이브 & 리뷰)
    index: 4
    period: 2022.5 ~ 2022.10
    info : |
        * Python
        * Django
        * JavaScript
        * HTML
        * CSS
    person: 
        * 개발 2명
    incharge: |
        * 팀 리더
        * Back-End 개발
        * Front-End 개발
        * Back Office 개발
    description: |
        * <mark>스타트업데이 1등</mark>으로 회사 내 시스템 도입 시도
        * 한섬 라이브 방송 <mark>채팅 분석</mark> 시스템 개발
        * 한섬 상품 텍스트 데이터 <mark>리뷰 분석</mark> 시스템 개발
        * 긍정어, 부정어 구분 기능
        * Hot Keyword 분석 기능
        * 가장 많이 언급된 키워드 분석 기능
        * H Fashion몰 라이브 커머스 데이터 활용

-   title: 라이브 커머스인 Shoplive API 개발
    index: 5
    period: 2021.7 ~ 2022.3
    info : |
        * Spring
        * Java
        * JSP
        * Rest API
        * JWT
        * OAuth 2.0
    person: 
        * 기획 1명, 앱개발 1명, 웹개발 1명
    incharge: |
        * Back-End 개발
        * Front-End 개발
        * Back Office 개발
        * H Fashion몰 개발
    description: |
        * <mark>라이브 커머스 신규 페이지</mark> 생성
        * 라이브 방송 댓글을 위한 회원 인증 JWT, OAuth 2.0 적용
        * Rest API로 예정된 방송, 실시간 방송, 종료된 방송 API 개발
        * 방송 중 쿠폰 다운로드 개발
        * 방송 중 장바구니 기능 개발 
