-   title: 리뷰 API인 Crema API 도입 프로젝트
    index: 1
    period: 2023.10 ~ 2024.09
    info : |
        * Spring batch
        * Java
        * Spring
        * Rest API
    description: |
        * 상품, 주문, 주문상세&클레임, 리뷰, 카테고리 API 개발 및 연동 (`23.10 - `24.02)
        * 상품, 주문, 주문상세&클레임 리뷰는 단 건 전송 이후 List 전송으로 v2 개발 (`24.03 - `24.08)
        * List로 변경하여 인터페이스 내역 감소로 인한 장애 대응
            * 주문 36만건 → 1만건 (누적 데이터 97%감소)
            * 주문 상세&클레임 67만건 → 8천건 (누적 데이터 98%감소)
            * 상품 3만건 → 2천건 (누적 데이터 94%감소)
        * FitProduct API 개발을 위해 상품 상세 사이즈 정보 전체 파싱 개발
        * Crema API인 주문, 주문상세&클레임 쿼리 전체 수정 작업 진행
            * 주문 3.19sec → 0.02sec
            * 주문상세 3.73sec → 0.47sec
            * 클레임 2.96sec → 0.13sec
        * H패션몰 H.Plus 포인트 적립에서 한섬 마일리지로 적립 전환을 위한 마일리지 API 개발
        
-   title: RPA 개발자, 웹 개발자
    index: 2
    company: (주) 대림
    period: 2020.01.01 ~ 2020.12.31
    domain: ERP
    info : |
        * RPA
        * WEB
        * DL 계열사
    description: |
        * IT사업부 제조SM팀 / 주임
        * 물류 시스템 (Dlogis) Web 시스템 개발 및 운영
        * <mark>RPA</mark>를 이용한 <mark>물류 세금 자동화 처리 시스템</mark> 개발 및 운영 (최초 도입)
